project:
  name: nt548-lab2-task2
  regions:
    - ap-southeast-2

tests:
  lab2-task2-infra:
    template: ./group_18.yaml
    parameters:
      KeyName: huyt-ec2-key
      AmiId: ami-0b8d527345fdace59
      InstanceType: t3.small
      AllowedSshCidr: 0.0.0.0/0
